// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqvqbaqhwjbjvkyjgvjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdnFiYXFod2pianZreWpndmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDU1MTksImV4cCI6MjA2NzA4MTUxOX0.5gbUEOXAlG7sCw-f_tB7PAyORLJugNolAhEcACvJgUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});