// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pahvcbsuygjsrgeugedt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhaHZjYnN1eWdqc3JnZXVnZWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzQxMzEsImV4cCI6MjA2NjY1MDEzMX0.yuxnwAEogsR3R6pqjlnY9oxONMRuz88cw32GGoee3i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});